import { type NextPage } from "next";
import Head from "next/head";
import React, { useState, useEffect, useCallback } from "react";
import BasicButton from "./components/Button";

const Home: NextPage = () => {
  const lastElement = React.createRef<HTMLDivElement>();
  const [height, setHeight] = useState(null);
  useEffect(() => {
    if (typeof window !== "undefined") {
      setHeight(window.innerHeight);
    }
  }, []);
  return (
    <div className="max-h-screen min-h-screen overflow-hidden bg-gray-100">
      <Head>
        <title>Don't rush it !</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-start overflow-hidden bg-gradient-to-b from-[#100F5B] to-[#155A73] py-5">
        <div className="container flex flex-col items-center justify-start gap-12 rounded-xl  px-4">
          <h1 className="text-xl tracking-tight text-white sm:text-[3rem]">
            DON'T{" "}
            <span className="font-bold text-[hsl(280,100%,70%)]">RUSH</span> IT
            !
          </h1>
        </div>

        <div
          style={{
            height: height * 0.79,
          }}
          className=" relative my-8 w-11/12  gap-12 overflow-hidden rounded-xl bg-gray-900 py-4 px-4  text-white opacity-80"
        >
          <div
            className={
              "absolute flex h-8 w-full items-center justify-center  align-middle "
            }
          >
            <div className={"h-full w-28  rounded-b-lg bg-gray-700 opacity-70"}>
              <p className={"z-20 text-center text-lg text-white"}>
                ⚛️Index.ts
              </p>
            </div>
            <div className={"absolute right-8 top-0"}>
              <button
                onClick={() => {}}
                className={`h-8 rounded-bl-lg rounded-tr-lg bg-green-500 px-4 py-1 text-white`}
              >
                Finish !
              </button>
            </div>
          </div>

          <div
            className={
              "  zen-10 h-full w-full self-center overflow-y-auto rounded-lg bg-gray-800 p-4 scrollbar-hide"
            }
          >
            {/*
            <CodeMirror
              value="console.log('hello world!');"
              theme={myTheme}
              extensions={[javascript({ jsx: true })]}
              onChange={onChange}
              maxWidth={(window.innerWidth * 0.5).toString()}
              style={{
                outline: "none",
                border: "none",
                margin: 0,
                padding: 0,
                borderRadius: 0,
                borderColor: "transparent",
              }}
              basicSetup={{
                foldGutter: true,
                highlightActiveLineGutter: false,
                lineNumbers: true,
                indentOnInput: true,
              }}
            />
            */}
            <div ref={lastElement}></div>
          </div>
        </div>
        <footer className=" relative bottom-5 flex w-full flex-row justify-evenly">
          <BasicButton
            text="Give up :("
            onClick={() => {}}
            tailwindProps="bg-pink-800 rounded-md"
          />
          <BasicButton
            text="Finish !"
            onClick={() => {}}
            tailwindProps="bg-green-900 rounded-md"
          />
        </footer>
      </main>
    </div>
  );
};

export default Home;
